layout_version: marker_layout_v2_calibrated
dictionary: DICT_4X4_50
image:
  width: 800
  height: 600
calibration:
  frame_id: '1'
  image_path: data\raw_sessions\session_16\frames\000001.jpg
  outer_anchor_rule: ID0_outer_TL, ID2_outer_TR, ID5_outer_BR, ID3_outer_BL
  dst_outer:
  - - 45.0
    - 45.0
  - - 755.0
    - 45.0
  - - 755.0
    - 555.0
  - - 45.0
    - 555.0
description: 'Calibrated six-marker layout. Corner order is the same as OpenCV ArUco
  detection order for each marker: top-left, top-right, bottom-right, bottom-left
  in marker coordinate.'
markers:
  0:
    name: top_left
    row: top
    col: left
    corners:
    - - 45.0
      - 45.0
    - - 147.34
      - 47.75
    - - 149.18
      - 146.78
    - - 46.98
      - 146.54
  1:
    name: top_center
    row: top
    col: center
    corners:
    - - 343.76
      - 46.28
    - - 447.06
      - 46.0
    - - 448.98
      - 144.23
    - - 346.91
      - 143.99
  2:
    name: top_right
    row: top
    col: right
    corners:
    - - 644.46
      - 39.9
    - - 755.0
      - 45.0
    - - 753.77
      - 160.79
    - - 640.2
      - 158.17
  3:
    name: bottom_left
    row: bottom
    col: left
    corners:
    - - 43.44
      - 442.16
    - - 158.7
      - 442.92
    - - 158.45
      - 554.32
    - - 45.0
      - 555.0
  4:
    name: bottom_center
    row: bottom
    col: center
    corners:
    - - 342.49
      - 443.57
    - - 454.92
      - 445.2
    - - 458.04
      - 556.65
    - - 344.1
      - 557.31
  5:
    name: bottom_right
    row: bottom
    col: right
    corners:
    - - 644.15
      - 443.19
    - - 752.36
      - 446.22
    - - 755.0
      - 555.0
    - - 646.3
      - 552.26
quality_rules:
  min_markers: 3
  min_points: 12
  require_both_rows: true
  min_column_span: 2
  ransac_reproj_threshold: 5.0
  min_inlier_ratio: 0.7
  max_reprojection_error: 8.0
fallback:
  use_previous_h: true
  max_fallback_gap: 2
